const CONFIG = {
    introTitle: 'Bé à!',
    introDesc: `Mọi người hướng về 4 phương còn anh chỉ hướng về Phương Ngọc thuiii`,
    btnIntro: 'hihi',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Vẫn cứ là thích anh <33',
    btnNo: 'Ko yêu t đấm cho ' :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao anh lại yêu em <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Anh yêu công chúa.',
    btnAccept: 'Okiiiii lun <3',
   }
